name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "36 3,10,20,23 * * *"
  workflow_dispatch:

jobs:
  autogreen:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Git configuration
        run: |
          git config --local user.email "g070893857403@outlook.com"
          git config --local user.name "Zheng-Zihan403"

      - name: Make changes
        run: |
          echo "Changes made at $(date)" >> changes.txt
          git add changes.txt

      - name: Commit and push changes
        run: |
          git commit -m "update changes.txt"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
